# Site settings
title: Mapa PyAr Docentes
description: Encontrá a tu profe de Python
baseurl: "/mapa-pyar-docentes" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mapa PyAr Docentes
user_description: Encontrá a tu profe de Python
user_title: Encontrá a tu profe de Python
email: bibiana.rivadeneira@gmail.com
#twitter_username: lorem_ipsum
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
#  - title: Home
#    url: /
#  - title: Series
#    url: /series
#  - title: Tags
#    url: /tags
#  - title: About Me
#    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
